name: Slack Notification
on: push
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_USERNAME: 알림이
